spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456 # 你之前 docker run 设置的密码
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 首次启动用 create，表创建成功后改回 update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# 对应你文档里的 RustFS 配置
app:
  storage:
    endpoint: http://localhost:9000
    access-key: LRtfPuiqDTY673XEvpFW
    secret-key: lJEak8p0qzcOibugWjs5RFrvehHdTwxGC9KPLDZ2 # 这里确认下你 RustFS 启动时是否有默认密钥
    bucket: interview-guide
    region: us-east-1